using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using JKD.Models;
using JKD.DB;
using System.IO;

namespace JKD.CenterView
{
    public partial class EmployeeControl : DevExpress.XtraEditors.XtraUserControl
    {
        public List<Employee> li = new EmployeeManager().GetList();
        public EmployeeControl()
        {
            li = new EmployeeManager().GetList();
            InitializeComponent();
            gridControl1.DataSource = li;
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
          
        }
    }
}
