using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using JKD.Dialog;
using JKD.DB;
using JKD.Models;
using DevExpress.XtraGrid.Columns;

namespace JKD.CenterView
{
    public partial class MyJKControl : DevExpress.XtraEditors.XtraUserControl
    {
        public Account SelectedAccount  ;
        public MyJKControl()
        {
            InitializeComponent();
            Init();

            // This line of code is generated by Data Source Configuration Wizard
            // Uncomment next line to set the total number of data records stored within your source
            // unboundSource1.SetRowCount(42);
            // This line of code is generated by Data Source Configuration Wizard
            this.unboundSource1.ValueNeeded += unboundSource1_ValueNeeded;
            // This line of code is generated by Data Source Configuration Wizard
            this.unboundSource1.ValuePushed += unboundSource1_ValuePushed;
            // This line of code is generated by Data Source Configuration Wizard
            // Uncomment next line to set the total number of data records stored within your source
            // unboundSource1.SetRowCount(42);
            // This line of code is generated by Data Source Configuration Wizard
            this.unboundSource1.ValueNeeded += unboundSource1_ValueNeeded_1;
            // This line of code is generated by Data Source Configuration Wizard
            this.unboundSource1.ValuePushed += unboundSource1_ValuePushed_1;
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new System.ComponentModel.BindingList<JKD.Models.Jkd>() /* TODO: Assign the real data here.*/;
        }
        public void Init()
        {
            this.deBegin.Text = DateTime.Now.ToString("yyyy-MM-dd");
            this.deEnd.Text = DateTime.Now.ToString("yyyy-MM-dd");
            this.sbQuery.Click += RefeshData;
            this.cbeJKR.Properties.Items.Add("所有");
            foreach(DataRow datarow in SqlHelper.ExecuteTable("select distinct jkr from account").Rows)
            {
                this.cbeJKR.Properties.Items.Add(datarow["jkr"]);
            }
            this.cbeJKR.SelectedIndex = 0;
            this.groupControl1.CustomButtonClick += (s, e) =>
            {
                if (e.Button.Properties.Caption == "新增") {
                    SelectedAccount = new Account();
                    DialogFactory.CreateJKDControl(SelectedAccount);
                }else if (e.Button.Properties.Caption == "查看")
                {
                    DialogFactory.CreateJKDControl(SelectedAccount);
                }else if (e.Button.Properties.Caption == "删除")
                {
                    DialogResult dr = XtraMessageBox.Show("是否确定删除该记录?", "确认框", MessageBoxButtons.OKCancel);
                    if(dr == DialogResult.OK)
                    {
                        int count = new AccountManager().Delete(SelectedAccount.id);
                        if (count > 0)
                        {
                            XtraMessageBox.Show($"Id为{SelectedAccount.id}的记录删除成功");
                        }
                    }
                    
                }
                this.RefeshData(this, new EventArgs());
              
            };

        }
        public void RefeshData(Object sender,EventArgs e)
        {
            List<Jkd> li = new JkdManager().GetList(deBegin.Text + " 00:00:00", deEnd.Text + " 23:59:59", cbeJKR.Text);
            MoneyConvertChinese mcc = new MoneyConvertChinese();
            li.ForEach(item => item.JeDX = mcc.MoneyToChinese(item.Je.ToString()));
            gridControl1.DataSource = li.Where(item=>item.Isdelete==0).ToList();

        }
        

        private void gridView1_FocusedRowObjectChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            //获得选中的行，如果是单选模式，则直接取第一个
            int selectRow = advBandedGridView1.GetSelectedRows()[0];
            //获得绑定的行数据
            //  DataRow dataRow = gridView1.GetDataRow(selectRow);
            Jkd myjkd= advBandedGridView1.GetRow(selectRow)  as Jkd;
            SelectedAccount = new Account()
            {
                id = myjkd.Id,
                accid   =myjkd.Accid,
                dysj=myjkd.Dysj,
                jkrq=myjkd.Jkrq,
                je=myjkd.Je,
                kxly=myjkd.Kxly,
                lrsj=myjkd.Lrsj,
                jkr=myjkd.Jkr,
                isdelete=myjkd.Isdelete,
                bz=myjkd.Bz

            };
            

        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValueNeeded(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {

            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValuePushed(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {

            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValueNeeded_1(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {

            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValuePushed_1(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {

            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }
    }
}
